# -*- coding: utf-8 -*-
"""Análise Gutenberg - O Médico e o Monstro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qFnMnrQ4YhiYB5vFRGRZhKkPVN4F9n8k

# Tarefa

## Avaliações e análises de obras literárias em inglês disponíveis no Projeto Gutenberg

Cada grupo (4-5 componentes) deverá realizar as seguintes tarefas, a partir de corpus pré-definidos do Projeto Gutenberg.

- Encontrar e carregar o corpus de texto indicado para seu grupo.
- Realizar o pré-processamento do texto, executando as etapas que achar necessárias.
- Calcular e exibir graficamente a distribuição de frequência das vinte palavras mais comuns, excluindo *stopwords*.
- Apresentar graficamente os 10 bigramas mais comuns do texto processado.
- Apresentar graficamente os dez trigramas mais comuns do texto processado.
- Escolher três palavras, três bigramas e três trigramas representativos e aplicar uma análise de concordância e similaridade. Justifique suas escolhas e apresente o resultado.
- Você conseguiria estabelecer uma relação entre cada um dos três grupos de análises do item anterior e o contexto da obra analisada? Em outras palavras: as palavras, bigramas e trigramas escolhiodos, a partir dos mais representativos, realmente representam a obra literária onde aparecem. Justifiquem as respostas.

**A apresentação dos resultados de cada grupo deverá ser feita na aula do dia 07/10/2025, após a vista de prova. O formato de apresentação é livre e deverão ser apresentados, pelo menos, as informações pedidas acima. Máximo de 10 minutos por grupo. O trabalho também será entregue no mesmo dia, via e-mail, para `cassius.figueiredo@professores.ibmec.edu.br`.**

## **Corpora**

- 1) **Frankenstein**, Mary Wollstonecraft Shelley
- 2) **Moby Dick**, Herman Melville
- 3) **Alice's Adventures in Wonderland**, Lewis Carroll
- 4) **The Strange Case of Dr. Jekyll and Mr. Hyde**, Robert Louis Stevenson
- 5) **Dracula**, Bram Stoker
- 6) **The Adventures of Sherlock Holmes**, Arthur Conan Doyle
- 7) **A Christmas Carol**, Charles Dickens
- 8) **The Wonderful Wizard of Oz**, L. Frank Baum
- 9) **Gulliver's Travels**, Jonathan Swift
- 10) **The War of the Worlds**, H. G. Wells
- 11) **Treasure Island**, Robert Louis Stevenson
- 12) **Don Quixote**, Miguel de Cervantes Saavedra
- 13) **The Life and Adventures of Robinson Crusoe**, Daniel Defoe
- 14) **Twenty Thousand Leagues under the Sea**, Jules Verne
- 15) **Around the World in Eighty Days**, Jules Verne
- 16) **A Journey to the Centre of the Earth**, Jules Verne

## **Lista de grupos e livros escolhidos**

- GRUPO 01 (Breno França, Isabella, Fabiano, Thiago Brandão, João Pedro Menezes) (6)
- GRUPO 02 (Breno Souza, Mateus Padilha, Gustavo Raia, Ian Esteves, Brenda) (4)
- GRUPO 03 (Gabriel Franklin, João Gabriel, Rafael, Thais, André) (10)
- GRUPO 04 (Fernanda, Juliana, Maria, Larissa, João Araújo) (3)
- GRUPO 05 (Ivo, Pedro, Mateus Norcia, Rodrigo, Matheus Cocenzo) (8)
- GRUPO 06 (Daniel, João Vitor, Luis Pastura, Thiago Borsoni, Matheus Peçanha) (11)
- GRUPO 07 (Amanda, Beatriz, Guilherme Duran, Laura, Gabriel Mendes) (12)

# Solução

## Configuração Básica

### Importação das Bibliotecas Necessárias
"""

# You may need to run these once in your environment (e.g., Colab, Jupyter, etc.)
# !pip install requests nltk matplotlib

import requests
import re
import math
import nltk
import matplotlib.pyplot as plt
from collections import Counter
from wordcloud import WordCloud, STOPWORDS

nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk import bigrams, trigrams

"""### Importação do Livro - O Médico e o Monstro (_The Strange Case of Dr. Jekyll and Mr. Hyde_)"""

# URL do Livro Disponível no Site do Projeto Gutenberg
url = "https://www.gutenberg.org/files/42/42-0.txt"

response = requests.get(url)
text = response.text[1509:142685]

# Removendo Prefácio, Índice e Dedicatória
print(text)

"""## Pré-Processamento de Texto"""

# Convertendo Texto para Lowercase
text = text.lower()

# Limpeza de Dados (Mantém apenas Letras e Espaços)
text = re.sub(r'[^a-z\s]', '', text)

# Tokenização
tokens = word_tokenize(text)

# Exemplo com as Stopwords
print("Primeiras 5 palavras (com stopwords):\n\n" + "\n".join([str(tok) for tok in tokens[:5]]))

"""### Remoção de Stopwords (Inglês)"""

# Definindo as Stopwords (Padrão)
stop_words = set(stopwords.words("english"))

# Remoção de Stopwords
filtered_tokens = [word for word in tokens if word not in stop_words]

# Exemplo sem as Stopwords
print("Primeiras 5 palavras (sem stopwords):\n\n" + "\n".join([str(tok) for tok in filtered_tokens[:5]]))

"""## Plots

### Distribuição de Frequência
"""

# Contagem de Frequência das Palavras
word_counts = Counter(filtered_tokens)

# Pega as 20 Palavras que Mais Aparecem (Já sem Stopwords)
most_common_20 = word_counts.most_common(20)

# Comando novo que não conheciamos
words, counts = zip(*most_common_20)

# Plot
plt.figure(figsize=(12,6))
bars = plt.bar(words, counts)
plt.title("20 Palavras Mais Utilizadas em O Médico e o Monstro")
plt.bar_label(bars)
plt.xticks(rotation=45)
plt.ylabel("Quantidade")
plt.show()

"""### Representação em Wordcloud"""

list_most_common_20 = []
for i in most_common_20:
    list_most_common_20.append(i[0])

text = " ".join(list_most_common_20)
wordcloud = WordCloud(background_color="white",width=2000, height=800, collocations = False).generate(text)
fig = plt.figure(figsize=(11,7))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

"""### Função para Calcular N-Gramas"""

def ngrams_list(tokens, n):
    """Retorna a Lista dos N-Gramas como Strings 'w1 w2 ... wn'."""
    return [' '.join(tokens[i:i+n]) for i in range(len(tokens) - n + 1)]

"""### Bigramas

#### Tokens 1
"""

bigram_list = ngrams_list(filtered_tokens, 2)

bigram_counts = Counter(bigram_list)

most_common_10_bigrams = bigram_counts.most_common(10)

labels, counts = zip(*most_common_10_bigrams)

plt.figure(figsize=(12,6))
bars = plt.bar(labels, counts)
plt.title("10 Bigramas Mais Comuns")
plt.xticks(rotation=45, ha='right')
plt.ylabel("Quantidade")
plt.bar_label(bars, fmt='%d', padding=3)
plt.tight_layout()
plt.show()

"""#### Teste: Remoção de Palavras Pequenas (mr, sr, sir)"""

# Remoção de Stopwords + Retirada de Palavras Pequenas
filtered_tokens_2 = [word for word in tokens if word not in stop_words and len(word)> 3]

"""#### Tokens 2"""

bigram_list_2 = ngrams_list(filtered_tokens_2, 2)

bigram_counts_2 = Counter(bigram_list_2)

most_common_10_bigrams_2 = bigram_counts_2.most_common(10)

labels_2, counts_2 = zip(*most_common_10_bigrams_2)

plt.figure(figsize=(12,6))
bars = plt.bar(labels_2, counts_2)
plt.title("10 Bigramas Mais Comuns")
plt.xticks(rotation=45, ha='right')
plt.ylabel("Quantidade")
plt.bar_label(bars, fmt='%d', padding=3)
plt.tight_layout()
plt.show()

"""### Trigramas

#### Tokens 1
"""

trigram_list = ngrams_list(filtered_tokens, 3)

trigram_counts = Counter(trigram_list)

most_common_10_trigrams = trigram_counts.most_common(10)

t_labels, t_counts = zip(*most_common_10_trigrams)

plt.figure(figsize=(12,6))
bars = plt.bar(t_labels, t_counts)
plt.title("10 Trigramas Mais Comuns")
plt.xticks(rotation=45, ha='right')
plt.ylabel("Quantidade")
plt.bar_label(bars, fmt='%d', padding=3)
plt.tight_layout()
plt.show()

"""#### Tokens 2"""

trigram_list_2 = ngrams_list(filtered_tokens_2, 3)

trigram_counts_2 = Counter(trigram_list_2)

most_common_10_trigrams_2 = trigram_counts_2.most_common(10)

t_labels, t_counts = zip(*most_common_10_trigrams_2)

plt.figure(figsize=(12,6))
bars = plt.bar(t_labels, t_counts)
plt.title("10 Trigramas Mais Comuns")
plt.xticks(rotation=45, ha='right')
plt.ylabel("Quantidade")
plt.bar_label(bars, fmt='%d', padding=3)
plt.tight_layout()
plt.show()

"""## Análise de Concordância e Similaridade"""

livro_text = nltk.Text(filtered_tokens)

"""### Palavras

#### Lawyer (Advogado)
"""

livro_text.concordance('lawyer')

livro_text.similar('lawyer')

"""#### Door (Porta)"""

livro_text.concordance('door')

livro_text.similar('door')

"""#### Man (Homem)"""

livro_text.concordance('man')

livro_text.similar('man')

"""### Bigramas

#### Dr Jekyll
"""

livro_text.concordance(['dr', 'jekyll'])

livro_text.common_contexts(['dr', 'jekyll'])

"""#### Said Lawyer"""

livro_text.concordance(['said', 'lawyer'])

livro_text.common_contexts(['said', 'lawyer'])

"""#### Mr Hyde"""

livro_text.concordance(['mr', 'hyde'])

livro_text.common_contexts(['mr', 'hyde'])

"""### Trigramas

#### Dr Jekyll Home
"""

livro_text.common_contexts(['dr', 'jekyll', 'home'])

livro_text.concordance(['dr', 'jekyll', 'home'])

"""#### Poor Harry Jekyll"""

livro_text.common_contexts(['poor', 'harry', 'jekyll'])

livro_text.concordance(['poor', 'harry', 'jekyll'])

"""#### Envelope Addressed Hand"""

livro_text.common_contexts(['envelope', 'addressed', 'hand'])

livro_text.concordance(['envelope', 'addressed', 'hand'])

"""# Conclusão

A Análise serviu para mostrar que a forma narrativa do texto afeta a análise do texto e que, por conta disso, a presença do nome dos personagens de forma constante em bigramas e trigramas evidencia isso.
"""